#!/usr/bin/env sh

#
# [dotfiles/install]
#
# my dotfiles installer.
# copyright (c) 2018-2019, liam schumm.
#

echo "installing .bash_profile..."
cp bash_profile ~/.bash_profile

echo "installing .init.el..."
cp init.el ~/.emacs.d/init.el

echo "installing ssh_config (will require root password)..."
sudo cp ssh_config /etc/ssh/ssh_config

echo "installing gitconfig..."
cp gitconfig ~/.gitconfig

echo "setting wallpaper..."
osascript -e "tell application \"Finder\" to set desktop picture to POSIX file \"$(pwd)/wallpaper.jpg\""

echo "supressing terminal login message..."
touch ~/.hushlogin

echo "ensuring ~/Desktop/.bin folder exists..."
mkdir -p ~/Desktop/.bin

echo "installation complete."
