version: '3'

services:
  bitwarden:
    image: bitwardenrs/server
    restart: always
    volumes:
      - /bitwarden/data:/data
    environment:
      WEBSOCKET_ENABLED: "false"
      SIGNUPS_ALLOWED: "false"
      DOMAIN: "https://bitwarden.hexdump.cloud"
      LETSENCRYPT_EMAIL: ""
      SMTP_HOST: ""
      SMTP_FROM: ""
      SMTP_PORT: "25"
      SMTP_SSL: "true"
      SMTP_USERNAME: ""
      SMTP_PASSWORD: ""
      LOG_FILE: "/data/bitwarden.log"
      LOG_LEVEL: "warn"
      TZ: "America/Chicago"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.bitwarden-insecure.entrypoints=web"
      - "traefik.http.routers.bitwarden-insecure.rule=Host(`bitwarden.hexdump.cloud`)"
      - "traefik.http.routers.bitwarden.entrypoints=websecure"
      - "traefik.http.routers.bitwarden.rule=Host(`bitwarden.hexdump.cloud`)"
      - "traefik.http.routers.bitwarden.tls=true"
      - "traefik.http.routers.bitwarden.tls.certresolver=myresolver"
      - "traefik.docker.network=reverse-proxy"
    networks:
      - reverse-proxy

networks:
  reverse-proxy:
    external:
      name: reverse-proxy