version: '3'

services:
  db:
    image: mariadb:10.3.22
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    restart: always
    volumes:
      - /nextcloud/data/db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=
    env_file:
      - db.env

  app:
    image: nextcloud:apache
    restart: always
    volumes:
      - /nextcloud/data/nextcloud:/var/www/html
    environment:
      - VIRTUAL_HOST=nextcloud.hexdump.network
      - LETSENCRYPT_HOST=nextcloud.hexdump.network
      - LETSENCRYPT_EMAIL=
      - MYSQL_HOST=db
    env_file:
      - db.env
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nextcloud-insecure.entrypoints=web"
      - "traefik.http.routers.nextcloud-insecure.rule=Host(`nextcloud.hexdump.cloud`)"
      - "traefik.http.routers.nextcloud.entrypoints=websecure"
      - "traefik.http.routers.nextcloud.rule=Host(`nextcloud.hexdump.cloud`)"
      - "traefik.http.routers.nextcloud.tls=true"
      - "traefik.http.routers.nextcloud.tls.certresolver=myresolver"
      - "traefik.docker.network=reverse-proxy"
    depends_on:
      - db
    links:
      - db
    networks:
      - reverse-proxy
      - default

networks:
  reverse-proxy:
    external:
      name: reverse-proxy